

services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb+srv://chinh99078:eAUErOJRRQsb8ioT@project.rgihr.mongodb.net/test
      - JWT_SECRET=your_secret_key
      - CHATBOT_API_KEY=AIzaSyC1gzU8qfoK0gI1foldh3kze8ngymr4XaA
    networks:
      - app-network

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API=http://localhost:3000
      # - VITE_API=http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge